### ISSUE TITLE
[vs code] Authorizing sign in doesn't sign me into vs code

### ISSUE THREAD

**Issue by jasonwilczak** [karigari/vscode-chat#104]
- Extension Version: 0.5.9
- OS Version: Windows_7 Enterprise SP1 x64
- VSCode version: 1.27.1 (user setup)

I followed the instructions for adding it to our workspace and everything worked fine [(issue ref](https://github.com/karigari/vscode-chat/issues/50)).  I clicked 'sign in' from vs code and authorized in the browser and our workspace shows me as configured.

![image](https://user-images.githubusercontent.com/7635038/45234693-7f9a4f00-b2a4-11e8-80cf-388a1103dd90.png)

However, when I go back into VS code, it still says 'sign in with slack', i even tried manually adding the token, but no luck...

![image](https://user-images.githubusercontent.com/7635038/45234753-a6588580-b2a4-11e8-994b-ee72126ae53e.png)

My settings:
```
// Proxy URL for network connections to the Slack API.
  "chat.proxyUrl": null,

  // Slack token for authentication. Get yours here: https://api.slack.com/custom-integrations/legacy-tokens
  "chat.slack.legacyToken": null,

  // [Experimental] Open bot links inside VS Code. For travis-ci.org, set configuration ["travis"].
  "chat.providers": null
```

**Comment by arjun27** [comment]
Thanks for writing in @jasonwilczak, and apologies for this issue. This is not expected, and I want to make sure we fix this issue asap.

1. Can you share the logs from the output channel? You can click on "output" in the bottom bar and select "slack chat" in the dropdown (image for reference below)
2. Did you try reloading the window by any chance after setting the token? You can select "reload window" from the command palette (Ctrl+Shift+P on windows)
3. The step right after the authentication is to store the token in your system credential vault. Is it possible to check if tokens were saved there? We use `vscode-chat` as the service name to store tokens.

<img width="775" alt="44894585-1a77b400-ad0e-11e8-939e-51e6c2b09e75" src="https://user-images.githubusercontent.com/284612/45234919-d16ac580-b2f4-11e8-872e-b5783a3f6fd6.png">

**Comment by jasonwilczak** [comment]
Ok, so i did the reload and opened the output, but no dice, i even tried re-signing in with the output open:

![image](https://user-images.githubusercontent.com/7635038/45235286-672b3400-b2a6-11e8-9d5f-2f52cdb5f578.png)


How do I check the `vscode-chat` token setting?

**Comment by arjun27** [comment]
Thanks Jason. I don't have access to a Windows machine to know how the Windows credential manager works exactly, but I did find this link showing how to access it - [link](https://support.microsoft.com/en-in/help/4026814/windows-accessing-credential-manager). We specify `vscode-chat` as the service name and `slack` as the account name for saving the credentials (using the [keytar](https://github.com/atom/node-keytar) library). Could you try searching credentials for either of those two keywords?

**Comment by jasonwilczak** [comment]
Sorry @arjun27 I was being dense, i found it and updated my comment with the info

**Comment by arjun27** [comment]
Thanks Jason, just noticed it. I'm investigating how this could fail; it's weird why the logs don't return an error - looks like a bug. Could you do one more check please? You can open up the dev tools view for vscode by running this command: "Toggle developer tools". Just want to see if there are any logs there that we could use to debug.

Thanks again for your patience1

**Comment by jasonwilczak** [comment]
Ok, so I did everything, opened dev tools, tried to re-authorize, opened the chat window, here is the output below.  The big error showed up when i tried opening the slack chat window.
```
workbench.main.js:sourcemap:4236 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///c%3A/Users/JWILCZAK/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///c%3A/Users/JWILCZAK/.vscode/extensions/ms-mssql.mssql-1.4.0/syntaxes/SQL.plist
e.register @ workbench.main.js:sourcemap:4236
workbench.main.js:sourcemap:3260 [karigari.chat]: View container 'vsliveshareTreeExplorerActivityBar' does not exist and all views registered to it will be added to 'Explorer'.
w._logMessageInConsole @ workbench.main.js:sourcemap:3260
workbench.main.js:sourcemap:1411  INFO no standard startup: not a new window
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/5944e81f3c46a3938a82c701f96d7a59b074cfdc/core/vs\workbench\workbench.main.js.map
workbench.main.js:3645 [Embedded Page] Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
workbench.main.js:3645 [Embedded Page] You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
workbench.main.js:1411   ERR Cannot destructure property `readTimestamp` of 'undefined' or 'null'.: TypeError: Cannot destructure property `readTimestamp` of 'undefined' or 'null'.
	at WebviewContainer.getAnnotatedMessages (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\webview\index.js:55:35)
	at WebviewContainer.update (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\webview\index.js:33:32)
	at ViewController.sendToUI (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\controller\index.js:143:25)
	at ViewController.handleInternal (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\controller\index.js:81:51)
	at ViewController.sendToExtension (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\controller\index.js:99:33)
	at panel.webview.onDidReceiveMessage (C:\Users\JWILCZAK\.vscode\extensions\karigari.chat-0.5.9\out\webview\index.js:29:61)
	at e.fire (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at e.$onMessage (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:793:833)
	at e._doInvokeHandler (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Users\JWILCZAK\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by arjun27** [comment]
Thank you, I should be able to use this to release a fix

**Comment by arjun27** [comment]
Hmm, turns out this is a harmless exception, but nevertheless needs a fix. I just saw that slack is down at the moment - [status page link](https://status.slack.com/2018-09/60787986d73e3949) - and that could be another reason for this. Let me ping here once that gets resolved

**Comment by jasonwilczak** [comment]
Sounds good and thanks for the response!  I should mention that I am in a corporate environment so I am not sure if there are any outbound calls that may be blocked?  I can access my slack workspace, obviously without issue but not sure if there is something else that is preventing the vs code extension from completing the sign in handshake.

**Comment by arjun27** [comment]
Yes, the corp environment could be a potential issue. We have historically solved that through the proxy url setting for other users.

Slack seems to be up now. We could give it a shot again whenever you can spare a minute. I will go through this again over the weekend to find any other potential issues. Thanks for your patience and help in digging through the logs!

**Comment by jasonwilczak** [comment]
Ok, will do.  Do you know what I can look for to see if a proxy is needed?

Really looking forward to using this we are just getting slack and live share approved and opened for use! 😁

**Comment by jasonwilczak** [comment]
Just an update, I tried at various points throughout the weekend and again this morning, but no luck, same behavior.  I tried to pay attention to any network traffic from vs code as well, but nothing.  It just seems to go dead when i tried to authorize via redirect or manual token setting.

**Comment by arjun27** [comment]
Thanks for trying it out again @jasonwilczak. I'm working on this and will get back to you with a fix for this shortly

**Comment by jasonwilczak** [comment]
Thanks @arjun27 !  I'll let you know if it works when the update drops.

**Comment by sbromberger** [comment]
Hi - sorry for jumping in, but I think I've got the same issue, but on OSX. I've configured the token manually and then reloaded the window. The only output I see is
```
[9/12/2018, 9:31:55 AM]: Activating Slack Chat
```

Not sure where to go from here.

**Comment by arjun27** [comment]
Thank you for reporting this @sbromberger, and apologies that you are running into this. My hunch so far was that it is related to the windows credential store, and knowing that you are on a Mac helps. I'm putting together a solution for this and will release a build in the next 24 hours.

One quick question - are you behind a network proxy by any chance? we have a configuration setting `chat.proxyUrl` that can be used to configure the url, just in case it applies for your case

**Comment by sbromberger** [comment]
> One quick question - are you behind a network proxy by any chance?

Yes, but it's fully transparent. There is no URL to configure.

**Comment by jasonwilczak** [comment]
Hi @arjun27 just wanted to check in and see if there was any progress or if there is anything I can do to assist?

**Comment by arjun27** [comment]
@jasonwilczak, apologies for the delay on this. With Seth’s help I was able to fix three network related issues

- vue.js not getting loaded from jsdelivr
- supporting self signed certificates 
- upgrading the underlying slack library since they have replaced their networking stack

I just want to add a debug command that collects relevant info in case the above don’t fix things for you. I should be able to release v0.5.10 in a few hours from now

**Comment by arjun27** [comment]
@jasonwilczak - I have released 0.5.10 to the marketplace with these fixes. Please give it a shot whenever you can. If you run into any issues, you can run the "Slack: Export diagnostic logs" command which will collect your local state to assist debugging

**Comment by sbromberger** [comment]
Just FYI, 0.5.10 works for me with `"chat.rejectTlsUnauthorized": false` set.

**Comment by jasonwilczak** [comment]
@arjun27 that sounds about right to me.  I will try and double check but I think that is our case.  I checked out the readme and the wording looks good.  Thanks a lot for all your help!

**Comment by arjun27** [comment]
ok great. I'll close this issue then

**Comment by sbromberger** [comment]
Thanks for the quick resolution. :)
