### ISSUE TITLE
[vscode] Add new chat provider: Discord

### ISSUE THREAD

**Issue by Splash15195** [karigari/vscode-chat#105]
My chat provider is Discord

- Extension Version: 0.5.9
- OS Version: Linux x64 4.15.0-33-generic
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
Thanks @Splash15195. Discord support is in #101. Will merge after some more testing

**Comment by arjun27** [comment]
@Splash15195, we have a pre-release build that supports Discord; you can set it up by following [these instructions](https://github.com/karigari/vscode-chat/pull/101#issuecomment-419648331). Please share if there is anything that does not work for you

**Comment by Splash15195** [comment]
**@arjun27** Thank you for the information, everything went well. So far it works perfectly

**Comment by arjun27** [comment]
That’s great to know. Feel free to share any suggestions or bug reports

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
