### ISSUE TITLE
[vscode] Add new chat provider: discord

### ISSUE THREAD

**Issue by MagicThunder02** [karigari/vscode-chat#108]
My chat provider is discord

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
Thanks for sharing @MagicThunder02. I just released a build that works with Discord. It's in a PR, but you can give it a shot right away: [see link](https://github.com/karigari/vscode-chat/pull/101#issuecomment-419648331). Please do share if there is anything that does not work for you

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
