### ISSUE TITLE
[vscode] Add new chat provider: discord

### ISSUE THREAD

**Issue by Neztlac** [karigari/vscode-chat#114]
My chat provider is discord

- Extension Version: 0.5.9
- OS Version: Linux x64 4.19.0-1-MANJARO
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
