### ISSUE TITLE
[vscode] Add new chat provider: discord

### ISSUE THREAD

**Issue by NeelAPatel** [karigari/vscode-chat#115]
My chat provider is discord

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.18234
- VSCode version: 1.26.0-insider

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
