### ISSUE TITLE
[vscode] Add new chat provider: hipchat

### ISSUE THREAD

**Issue by ferhat-hajdarpasic** [karigari/vscode-chat#116]
My chat provider is hipchat

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
thanks @ferhat-hajdarpasic. Hipchat is going to be discontinued - and therefore I'm going to close this. happy to re-open if that changes.
