### ISSUE TITLE
[vscode] Sign in with Slack failed: access_denied

### ISSUE THREAD

**Issue by Rtistx** [karigari/vscode-chat#120]
Sign in with Slack failed: access_denied

- Extension Version: 0.5.9
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
