### ISSUE TITLE
[vscode] Add new chat provider: Discord

### ISSUE THREAD

**Issue by misterhtmlcss** [karigari/vscode-chat#124]
My chat provider is Discord

- Extension Version: 0.5.9
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
