### ISSUE TITLE
[vscode] Add new chat provider: Discord

### ISSUE THREAD

**Issue by onuralpszr** [karigari/vscode-chat#132]
My chat provider is Discord

- Extension Version: 0.5.9
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
