### ISSUE TITLE
[vscode] Sign in with Slack failed: code_already_used

### ISSUE THREAD

**Issue by poohRab** [karigari/vscode-chat#145]
Sign in with Slack failed: code_already_used

- Extension Version: 0.5.11
- OS Version: Darwin x64 15.6.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Hi @poohRab, we have a bunch of solutions for slack auth listed here: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

I'm closing this for now, please re-open if there is anything I could help with
