### ISSUE TITLE
[oauth-service] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by PeteyRev** [karigari/vscode-chat#156]
- Extension version:0.6.1
- VS Code version: 1.27.2

I made sure my admin allowed it, the slack bot even told me that this app was now allowed

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
