### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by thientran-agilityio** [karigari/vscode-chat#168]
Sign in with slack failed: access_denied

- Extension Version: 0.6.1
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
