### ISSUE TITLE
[vscode] Add new chat provider: KurohPoha

### ISSUE THREAD

**Issue by Yukiiziinhhu** [karigari/vscode-chat#175]
My chat provider is KurohPoha

- Extension Version: 0.6.1
- OS Version: Windows_NT x64 6.3.9600
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
@Yukiiziinhhu - not sure if that is a valid chat provider, unable to find anything about it when I google. let me know if I got it wrong. will close this for now
