### ISSUE TITLE
"/live share" not working

### ISSUE THREAD

**Issue by johnpapa** [karigari/vscode-chat#19]
I typed `/live share` into the slack message textbox in vscode in a channel, private channel, and a direct message. None of them sent a link.

When I typed `/live end` it said "no session to end"

I love the idea of this extension! Great work!

**Comment by arjun27** [comment]
Thanks for writing in @johnpapa, and I'm sorry you ran into an issue. Most errors are shown as window notifications (like "no folder open"), but I found a scenario where this does not happen - when you are not signed in. In this case, the status bar gets stuck on "sharing..." indefinitely.

<img width="233" alt="screen shot 2018-07-02 at 12 43 18 am" src="https://user-images.githubusercontent.com/284612/42137875-973b1d9e-7d91-11e8-9cc5-119fc4e56418.png">

Is this the case for you? If so, signing in and then `/live share` should fix it. I might have a missed a different scenario, and @lostintangent's suggestion will help us debug it.

**Comment by johnpapa** [comment]
It appears i was not signed in. 

thanks

**Comment by johnpapa** [comment]
it would be nice to get some type of feedback , if the API supports it

**Comment by lostintangent** [comment]
@johnpapa We’ll fix this issue on the Live Share side. We currently silently fail when trying to share while the end-user isn’t signed in.
