### ISSUE TITLE
"New chat provider" issues noise

### ISSUE THREAD

**Issue by darkvertex** [karigari/vscode-chat#193]
There's 25 issues for "New chat provider: Microsoft Teams":
https://github.com/karigari/vscode-chat/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+microsoft+teams

I'm not the project manager but it might not hurt to do some de-duplication by finding if such an issue preexists instead of creating a fresh one every time. lol

**Comment by arjun27** [comment]
Thanks for the suggestion @darkvertex. Teams support is the top priority right now, and along with I'm also working on code changes to fix the issues noise
