### ISSUE TITLE
Validate access token after token input and show result to the user

### ISSUE THREAD

**Issue by loganintech** [karigari/vscode-chat#210]
### Issue description
I started to configure discord, added my access token, and got no prompt to select a default guild. Then I ran the "Change Workspace" command and no other window appeared, making the discord integration not work in entirety.

### Logs
 Installation id: true
Token configured: true
Current user available: false
Authentication result: not implemented
Websocket connected: false

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by loganintech** [comment]
```
Discord client log: Authenticated using token `REDACTED`
Discord client log: Using gateway wss://gateway.discord.gg/?v=6&encoding=json
Discord client log: [ws] [connection] Connecting to wss://gateway.discord.gg/?v=6&encoding=json
Discord client log: [ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&encoding=json
Discord client log: [ws] [connection] Identifying as a new session
Discord client log: [ws] [connection] Setting a heartbeat interval for 41250ms
Discord client log: [ws] [connection] Server closed the WebSocket connection: 4004
Discord client log: [ws] [connection] Clearing heartbeat interval
Discord client log: [ws] [connection] Tried to identify with an invalid token
Discord client log: [ws] [connection] Clearing heartbeat interval
Discord client log: [ws] [connection] Attempted to destroy WebSocket but no connection
```

Seems like discord thinks my token is invalid but I verified it many times. /shrug

**Comment by loganintech** [comment]
@arjun27 I verified it manually but I can go and try with another application and let you know in the next 24 hours.

**Comment by loganintech** [comment]
Hey @arjun27 just an update. I went to test it again and grabbed my token from the same place but this time it's working. I'm now willing to bet this wasn't an issue with your code but was probably an auth error of some kind. It could be nice to have a popup or some sort of notification that something went wrong though. Just my two cents :+1: Thank you for writing this.

**Comment by arjun27** [comment]
thanks @loganintech. I agree, we need a better approach to handle this. I'll update this issue to reflect that
