### ISSUE TITLE
[vscode] Add new chat provider: Discord

### ISSUE THREAD

**Issue by AliDoganKim** [karigari/vscode-chat#216]
My chat provider is Discord

- Extension Version: 0.6.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
Hey @alidogankim - the extension supports Discord. You can see the setup steps here https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md

Closing this issue for now. Let me know if you have any issues in setting it up
