### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by MarcelleBond** [karigari/vscode-chat#232]
Sign in with slack failed: access_denied

- Extension Version: 0.6.3
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.1

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. One of them should fix this for you, let me know
