### ISSUE TITLE
Something wrong during initialization of the extension

### ISSUE THREAD

**Issue by karenpommeroy** [karigari/vscode-chat#234]
- Extension Name: chat
- Extension Version: 0.6.3
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0
![screenshot_12](https://user-images.githubusercontent.com/93120/46793013-f794e280-cd44-11e8-957d-61a6bb518ae3.png)

 We have written the needed data into your clipboard. Please paste:

**Comment by arjun27** [comment]
thanks @karenpommeroy - this particular warning is harmless: it shows up when the VS Live Share extension is not installed. Apologies for the extra error message, I'll try to remove it.

Were you able to setup the extension for slack/discord? Let me know if there were any issues there
