### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by dinedal** [karigari/vscode-chat#241]
I am trying to sign in, redirect completes and I get an error that the extension can not access the keychain, how do I resolve?

- Extension Version: 0.6.3
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.27.2

**Comment by arjun27** [comment]
thanks for reporting this @dinedal. On Mac, the system keychain throws a password prompt to allow access to the keychain. Did you see anything like this after the redirect?

<img width="546" alt="screen shot 2018-10-15 at 9 13 32 am" src="https://user-images.githubusercontent.com/284612/46928938-9cbbfd80-d05a-11e8-84d7-d8d8db4167df.png">

**Comment by dinedal** [comment]
Nothing like that came up

**Comment by dinedal** [comment]
Okay, so I never got the prompt... but restarting vs-code seemed to do it? It worked now w/o error...

**Comment by arjun27** [comment]
thanks @dinedal. Not entirely sure why that worked. I'll update the current error handler to report the error message in case this happens for others too

**Comment by tristan957** [comment]
I am getting a similar issue. I have the extension working flawlessly on my home computer which is Linux, but I can't get the extension to work on mac
