### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by yolixtly** [karigari/vscode-chat#248]
Sign in with slack failed: access_denied

- Extension Version: 0.7.3
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.28.1

**Comment by arjun27** [comment]
Hi @yolixtly - thanks for reporting this. This issue can be resolved by some changes in your slack config. We have compiled a list of possible solutions to this here: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

I'll close this for now. Please re-open if there is anything I could help you with
