### ISSUE TITLE
[vscode] Sign in with slack failed: code_already_used

### ISSUE THREAD

**Issue by Jess-R** [karigari/vscode-chat#253]
Sign in with slack failed: code_already_used

- Extension Version: 0.7.3
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.28.2

**Comment by arjun27** [comment]
Hi @Jess-R  - thanks for reporting this. This issue can be resolved by some changes in your slack config. We have compiled a list of possible solutions to this here: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

I'll close this for now. Please re-open if there is anything I could help you with
