### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by nashtgc** [karigari/vscode-chat#255]
Sign in with slack failed: access_denied

- Extension Version: 0.7.3
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.2

**Comment by arjun27** [comment]
Hi @nashtgc - thanks for reporting this. This issue can be resolved by some changes in your slack config. We have compiled a list of possible solutions to this here: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

I'll close this for now. Please re-open if there is anything I could help you with
