### ISSUE TITLE
Unread message notification

### ISSUE THREAD

**Issue by gevorggalstyan** [karigari/vscode-chat#27]
It would be awesome to see the number of unread messages in the status bar, and also make it red or something when a new message arrives.

**Comment by arjun27** [comment]
Thanks for writing in. I've been thinking about using the status bar for this too, with the [StatusBarItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#StatusBarItem) API that shows an unread count. A notification badge is not supported by the API at this point. It'll be best to push this out after #5 and I'll link the two for now

**Comment by arjun27** [comment]
Now that #5 is done, I'm going to start on this. Will break this into 2 parts:

1. New messages after the extension has been activated: we will count the incoming messages and update the extension state, which will be used to populate the status bar item.
2. Unread count before the extension was activated: this will require querying the Slack API when the extension gets activated. Looks like [channels.list](https://api.slack.com/methods/channels.list) (the method we use) does not return `last_read`, but [channels.info](https://api.slack.com/methods/channels.info) does.

This might have some implications on message threads - which are not supported at this point (#7). Will look into that once we have threads support

**Comment by arjun27** [comment]
This is what we'll start with. Follow #33 for up-to-date progress :)

<img width="324" alt="screen shot 2018-08-08 at 5 36 56 pm" src="https://user-images.githubusercontent.com/284612/43836147-0710ffc2-9b32-11e8-9d17-d99b740853d2.png">

**Comment by arjun27** [comment]
With v0.5.1 we have covered both the aforementioned parts for this feature. Going to close this for now. Let's use new issues to track improvements
