### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by aminkh17** [karigari/vscode-chat#273]
Sign in with slack failed: access_denied

- Extension Version: 0.8.2
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.29.1

**Comment by arjun27** [comment]
Thanks @aminkh17. We have compiled a list of potential problems/solutions to this in this doc: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

Could you tell me if any of these apply to you? If not, I'd love to investigate further and find a fix for this. Thanks!

**Comment by aminkh17** [comment]
Thank you Arjun, I think the problem was Admin approval access. I have forwarded the link to the admin of our Slack group.
