### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Lucs1590** [karigari/vscode-chat#279]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.9.0`
- OS Version: `Linux x64 4.15.0-42-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/brito/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Thanks @Lucs1590. Could you also share the profiler result txt with the issue? Will help us debug the root case.

**Comment by Lucs1590** [comment]
How do I do this in vs code studio?

**Comment by arjun27** [comment]
Hey, I think vscode would have generated the file for you. Your earlier comment has the file location: `/home/brito/karigari.chat-unresponsive.cpuprofile.txt`. Can you access the generated file? If it's easier, you can also email the file to me at `arjun at rubberduck dot io`

**Comment by arjun27** [comment]
@Lucs1590 - I have released 0.9.1 with a fix for this. Let me know if you run into this again.
