### ISSUE TITLE
support corp proxy

### ISSUE THREAD

**Issue by d0uub** [karigari/vscode-chat#28]
seems not work with proxy? it shows nothing

**Comment by arjun27** [comment]
Thanks for sharing this issue, I'll look into this. Want to understand this better: does the following curl command work for your token from the terminal?

```
curl https://slack.com/api/auth.test\?token\=YOUR_TOKEN_HERE
```

Are you running the normal slack client on your system too? Is there any special proxy-related config there which we could learn from? A good next step might be to implement changes in #25

**Comment by d0uub** [comment]
for curl command i must include --proxy to make it work.
i am using normal slack client and it works, there is no any proxy configuration except windows proxy for slack.

**Comment by arjun27** [comment]
Thanks for checking. I believe we can replicate the curl behavior with the following changes to our slack client implementation
- https://slackapi.github.io/node-slack-sdk/web_api#custom-agent-for-proxy-support
- https://slackapi.github.io/node-slack-sdk/rtm_api#custom-agent-for-proxy-support

These will require the proxy address. Do you know if that is configured as an environment variable or are you manually specifying that for the curl command? Looks like Slack client is picking it up automatically from somewhere, and we could shoot for replicating that behavior

**Comment by d0uub** [comment]
yes i manaully specify --proxy after curl.
I have already config env http_proxy and https_proxy before i post here. but it (slack client) still work without those variables

**Comment by arjun27** [comment]
Ok, thanks. I'll make the change to use the env variables for now

**Comment by arjun27** [comment]
Released 0.4.5 on the marketplace with this fix. To use, setup the `chat.proxyUrl` configuration as given here https://github.com/karigari/vscode-chat#using-with-network-proxy

Will wait for you to confirm it works and then close this issue. Thx!

**Comment by d0uub** [comment]
work now, thanks

**Comment by baraneetharan** [comment]
Now it works. Thanks
