### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LucasOlmedo** [karigari/vscode-chat#283]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.9.0`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/lucas/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
thanks for reporting this @LucasOlmedo. we are looking at this in #279.

can you upload the cpuprofile file which is generated along with this?

**Comment by arjun27** [comment]
released 0.9.1 with a fix
