### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rlam3** [karigari/vscode-chat#284]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.9.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/raymondlam/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
@rlam3 - thanks for sharing this. we are tracking this in #279.

can you please upload the profiler result that has been generated? you would be able to locate it at: `/Users/raymondlam/karigari.chat-unresponsive.cpuprofile.txt`
