### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by meeshh** [karigari/vscode-chat#291]
[karigari.chat-unresponsive.cpuprofile.txt](https://github.com/karigari/vscode-chat/files/2737799/karigari.chat-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.9.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Meesh/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Thanks for sharing the profile output file. Will take a look and fix this asap

**Comment by arjun27** [comment]
Fixed in #55
