### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by burritosss** [karigari/vscode-chat#299]
Error: The user name or passphrase you entered is not correct.

- Extension Version: 0.10.0
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.30.2

I've seen some other issues like mine that are the same. I did get multiple passwords prompts requesting for keychain access but wouldn't go away after entering my password. After a couple of tries, I denied them all. Now I can't use the extension anymore. I tried restarting VSC and reinstalling the extension.

**Comment by arjun27** [comment]
thanks @burritosss. have you seen this issue with any other apps trying to use the keychain?

**Comment by burritosss** [comment]
> thanks @burritosss. have you seen this issue with any other apps trying to use the keychain?

No, I have not had this issue with any app nor have I had this with other VSC extensions.

**Comment by burritosss** [comment]
Is there a way to try and request keychain access again?

**Comment by arjun27** [comment]
Yes, you can run the flow again with the “Sign in with slack” or “Configure
access token” commands
-- 
http://arjun.is

**Comment by burritosss** [comment]
After I enter my discord token in the "Configure access token" flow it immediately shows the error message without giving me the keychain access prompt. Also if I enter a wrong token it gives another error for the wrong token. So restarting the "Configure access token" doesn't fix it for me.

**Comment by burritosss** [comment]
Also pressing the retry button just gives the same error instantly.

**Comment by arjun27** [comment]
Hmm, this isnt expected. It looks like the system isn’t allowing the app to access the keychain anymore. Is the error message consistent as the one you reported here earlier? “Incorrect user name/pass phrase”

Can you open the system keychain manually and check if it has any entries by the name “vscode-chat”?

**Comment by burritosss** [comment]
Yes the error message is consistently the same and there isn't a keychain entry named "vscode-chat".

**Comment by burritosss** [comment]
After restarting my pc this morning and opening VSC again, VSC prompted me for the keychain access. The extension now works again! Thanks for the help! and I am sorry to have wasted your time.

**Comment by arjun27** [comment]
great to know @burritosss. I still want to find a better fix for this though; access to the system keychain on macOS is failing for quite a few users. even though a random restart seems to fix it, it's not a solution. let me know if you have any ideas on this.
