### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by rsanjeeban** [karigari/vscode-chat#310]
Sign in with slack failed: access_denied

- Extension Version: 0.11.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.30.2

**Comment by arjun27** [comment]
Thanks for reporting @rsanjeeban. We have some potential solutions to this problem outlined in this doc: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

Could you tell me if any of them work for you?

**Comment by rsanjeeban** [comment]
**no. no one has work for me.
but i got the answer for this issue. thank you brother.** 😆😎
