### ISSUE TITLE
"set up" instead of "setup"

### ISSUE THREAD

**Issue by bobheadxi** [karigari/vscode-chat#318]
Perhaps a little pedantic, but "setup" is a noun/adjective, i.e. "follow the setup instructions", and **"set up"** is the verb, i.e. **"Set up Slack"**

https://www.merriam-webster.com/dictionary/setup
https://grammarist.com/spelling/set-up-vs-setup/

I can open a PR to fix these

**Comment by arjun27** [comment]
Sure, happy to merge this fix
