### ISSUE TITLE
[vscode] Unable to access keychain (ArchLinux)

### ISSUE THREAD

**Issue by alejack9** [karigari/vscode-chat#329]
Error: The name org.freedesktop.secrets was not provided by any .service files

- Extension Version: 0.11.0
- OS Version: Linux x64 4.20.11-arch1-1-ARCH
- VSCode version: 1.31.1

**Comment by alejack9** [comment]
Solved installing extra/gnome-keyring
(not provided in xfce4 by default)

**Comment by arjun27** [comment]
Nice, thanks for sharing @alejack9. This will be useful to other users who have a similar issue
