### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by Ajaymeledath** [karigari/vscode-chat#331]
Error: The name org.freedesktop.secrets was not provided by any .service files

- Extension Version: 0.11.0
- OS Version: Linux x64 4.4.0-142-generic
- VSCode version: 1.31.1

**Comment by arjun27** [comment]
Hi @Ajaymeledath, can you try installing extra/gnome-keyring in your system? That fixed a similar issue in #329
