### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by vikasgola** [karigari/vscode-chat#335]
Error: Unknown or unsupported transport 'disabled' for address 'disabled:'

- Extension Version: 0.12.0
- OS Version: Linux x64 4.15.0-45-generic
- VSCode version: 1.31.1

**Comment by arjun27** [comment]
Thanks for reporting this @vikasgola. Can you elaborate on what fixed it for you - or whether it's still not working? It might be useful for others

**Comment by vikasgola** [comment]
@arjun27 it's still not working.

**Comment by arjun27** [comment]
Thanks. We have seen many of these keychain failures (especially on Linux), and it will be useful for us to consider alternatives to the keychain. I'm tracking that in #325

**Comment by vikasgola** [comment]
@arjun27 Hey, I have found the issue.
It is related to keytar.js
