### ISSUE TITLE
Mac OS Cannot send messages.

### ISSUE THREAD

**Issue by mchtt** [karigari/vscode-chat#340]
Hello, I'm able to receive my teammates messages but when I input an answer , they don't receive it, yet they see me join the chat...
Also the avatar / surname is not displayed on my side ...

Mac OS Mojave 10.14.3
VS Code 1.32.1
<img width="563" alt="screenshot 2019-03-08 at 14 29 27" src="https://user-images.githubusercontent.com/7107299/54031297-a8959100-41ae-11e9-881e-acab1f9538e7.png">

**Comment by arjun27** [comment]
Thanks for reporting this @mchtt. Let me investigate this and get back to you soon

**Comment by arjun27** [comment]
In this screenshot, I'm assuming "salut" message is from the host, and when you send a message it doesn't work. Is that correct?

If so, from the debugging so far, it looks like the `liveshare.onDidChangePeers` callback was not triggered. I'm checking if there could be something else

**Comment by arjun27** [comment]
This should be fixed in 0.13.0. Please give it a shot and let me know if it works for you @mchtt
