### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ali92alaa** [karigari/vscode-chat#345]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

[karigari.chat-unresponsive.cpuprofile.txt](https://github.com/karigari/vscode-chat/files/2983020/karigari.chat-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Duplicate of #291
