### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by acsenrafilho** [karigari/vscode-chat#346]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Linux x64 4.10.0-38-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hotmicro/karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Duplicate of #291
