### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by justice092** [karigari/vscode-chat#348]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\alimo\karigari.chat-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Duplicate of #291
