### ISSUE TITLE
Slack @mention feature

### ISSUE THREAD

**Issue by PeteyRev** [karigari/vscode-chat#359]
I see that I can type in `<!here>` to mention everybody, but is there a way to do this for individual members?

**Comment by arjun27** [comment]
Thanks for sharing this @PeteyRev. Not possible at this stage. I'll use this issue to track progress on this. As always, happy to look into PRs for enhancements.

**Comment by PeteyRev** [comment]
@arjun27 Thanks, I will look into it. Awesome extension btw
