### ISSUE TITLE
Slack Messages Don't Update

### ISSUE THREAD

**Issue by burkeholland** [karigari/vscode-chat#36]
Slack messages are not updating. This is for messages that I send and receive. 

### Environment
MacOS: 10.13.6
VS Code: 1.25.1
Extension: 0.4.8

### Steps To Reproduce
Open Slack extension with either "Open" or "Change Channel".  Send a message. The messages do not show up. Click on the "Messages" notification in the bottom status bar. Click off that dropdown to return focus to Code. The error returned is `cannot read property map of undefined`.

https://www.screencast.com/t/AVG57YMn

**Comment by arjun27** [comment]
Thanks for reporting this @burkeholland. It was a bad regression in the latest update, and I have pushed 0.4.9 with the fix. Should be up on the marketplace in a few more minutes. Please don't hesitate to re-open if it doesn't work for you.

**Comment by arjun27** [comment]
Also, I noticed large unread counts in the video. Do they seem right to you? Unread counts is a new feature, and there might be an issue there too.
