### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aainai** [karigari/vscode-chat#361]
- Issue Type: `Performance`
- Extension Name: `chat`
- Extension Version: `0.12.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/atsushi/karigari.chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by arjun27** [comment]
Duplicate of #291
