### ISSUE TITLE
Theme name used in screenshots

### ISSUE THREAD

**Issue by maa3x** [karigari/vscode-chat#378]
Hi.

This extension is great! I like the color theme used in screenshot in the features section (middle image) which has the name `feature-2.png`.
**EDIT:** [link](https://raw.githubusercontent.com/karigari/vscode-chat/master/readme/feature-2.png)
I've searched the VS Code marketplace a lot, but couldn't find the color theme.
Can you give me it's name please?
Thank you.

**Comment by arjun27** [comment]
It’s called Code Blue

**Comment by arjun27** [comment]
https://marketplace.visualstudio.com/items?itemName=Sujan.code-blue

**Comment by wbeeftink** [comment]
Which theme is used in the first screenshot `preview.png`?

**Comment by arjun27** [comment]
One Dark Pro: https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme

**Comment by wbeeftink** [comment]
@arjun27 Thanks!
