### ISSUE TITLE
[vscode] Sign in with slack failed: code_already_used

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [karigari/vscode-chat#384]
Sign in with slack failed: code_already_used%0A%0A- Extension Version: 0.15.4%0A- OS Version: Linux x64 5.0.0-15-generic%0A- VSCode version: 1.34.0

**Comment by arjun27** [comment]
Please see https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md
