### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by CarlosMarioSom** [karigari/vscode-chat#385]
Sign in with slack failed: access_denied%0A%0A- Extension Version: 0.15.4%0A- OS Version: Linux x64 4.18.0-20-generic%0A- VSCode version: 1.34.0

**Comment by arjun27** [comment]
Thanks @CarlosMarioSom. Can you go through our docs on Slack access denied errors and see if anything there applies to you? https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md
