### ISSUE TITLE
Email address in Slack app listing does not work

### ISSUE THREAD

**Issue by challen0** [karigari/vscode-chat#398]
Hi,

I tried emailing the address listed on this page https://slack.com/apps/ACB4LQKN1-team-chat-for-vs-code but I got an undeliverable message back. Is there a better email address to list there?

**Comment by arjun27** [comment]
Thanks! I'll update the listing.

**Comment by arjun27** [comment]
In the meanwhile you can reach me directly: arjun at attam.in
