### ISSUE TITLE
Unable to login Slack in VS Code

### ISSUE THREAD

**Issue by aroraayush** [karigari/vscode-chat#47]
After I click on "Authorize" button on Slack OAuth Page, nothing happens

**Comment by arjun27** [comment]
In case you are on the updated VS Code, I've also added a fallback for such situations. It is available with v0.5.5 of the extension. If updating VS Code does not work, please update the extension to 0.5.5 and try signing in.

Thanks again for reporting this, and I hope it works for you after these changes.

**Comment by aroraayush** [comment]
Thanks for you help !! I managed to made it work by directly inputing the team- url/code created by the slack API

**Comment by arjun27** [comment]
Good to know. I'll close this issue for now. Feel free to create a new issue if you have an issue
