### ISSUE TITLE
[vscode] Sign in with Slack failed: access_denied

### ISSUE THREAD

**Issue by eb-viniciusp** [karigari/vscode-chat#50]
Sign in with Slack failed: access_denied

- Extension Version: 0.5.5
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.26.1

**Comment by arjun27** [comment]
Hey, thanks for reporting this @eb-viniciusp. Looks like the extension was not authorized during setup. Could you verify if that's the case?

If so, I would love to know what we could improve to make it work for you, and get the authorization approval?

**Comment by dwdozier** [comment]
I am having trouble getting 'signed in' too. I installed the extension, then use the sign in and I get a web page with 'Apologies, but you are not authorized to install Slack Chat for VS Code.' My guess is that there is some organizational level auth/permissions I don't have for my company's Slack instance.

**Comment by arjun27** [comment]
I investigated this, and from the error message that you have shared, it looks the app needs to be pre-approved by your workspace admins. Would it be possible for you to share this link with your admins for approval (remember to replace the subdomain)?

https://YOUR-WORKSPACE.slack.com/apps/ACB4LQKN1-slack-chat-for-vs-code

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
