### ISSUE TITLE
[oauth-service] Sign in with Slack failed: access_denied

### ISSUE THREAD

**Issue by TheoRev** [karigari/vscode-chat#56]
- Extension version:
- VS Code version:

**Comment by arjun27** [comment]
Thanks for reporting this @TheoRev. `access_denied` typically happens when this extension was denied permission during authorization. Can you help me verify if that was the case? Would love to know how we could improve the extension and make it work for you

**Comment by arjun27** [comment]
Added [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md) to detail potential solutions to this problem. Will close this issue for now - please feel free to create a new one if I have missed anything.
