### ISSUE TITLE
Unreads is counting joins/leavings as "unread"

### ISSUE THREAD

**Issue by darkvertex** [karigari/vscode-chat#62]
Perhaps there could be a preference to omit joins/leavings of channels from making them appear in the "UNREADS" section?

In my case in the official web client I have it set in my preferences to "hide conversations and channels unless unread" and am pretty caught up on messages but was surprised when I saw 20'ish channels or so marked unread from the extension's perspective.

After checking each one against the real Slack web app, I noticed they all had joins/leavings as the last messages, so I assume it must be that.

**Comment by arjun27** [comment]
Thanks @darkvertex, good catch! Digging into the Slack documentation gave me this

> unread_count is a full count of visible messages that the calling user has yet to read. unread_count_display is a count of messages that the calling user has yet to read that matter to them (this means it excludes things like join/leave messages)

We are using the `unread_count` key in the code. I'll make this change

**Comment by arjun27** [comment]
This has been fixed in v0.5.9
