### ISSUE TITLE
Date issue in VSCode

### ISSUE THREAD

**Issue by PrashanthHegdeSgr** [karigari/vscode-chat#66]
In VSCode invalid conversation date is showing (Month is showing as July instead of August).
I am raising this issue on 29/08/2018 but the conversation is showing **Sunday, July 29**
![issue-1](https://user-images.githubusercontent.com/16951635/44769080-0a7e9980-ab81-11e8-99eb-c80b60d3963c.jpg)

**Comment by arjun27** [comment]
Thanks for reporting this! I ran into this as well and fixed it with #60. I’m going to release 0.5.7 today with this fix

**Comment by arjun27** [comment]
0.5.7 has been released with this fix
