### ISSUE TITLE
[vscode] Add new chat provider

### ISSUE THREAD

**Issue by jeromehardaway** [karigari/vscode-chat#71]
My chat provider is: 

- Extension Version: 0.5.7
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.26.1

**Comment by mittalyashu** [comment]
What is the chat you want to be added to the `vscode-chat`?

**Comment by jeromehardaway** [comment]
Hi, I think this was automated when our company didn't allow VS Code to connect to our slack. I apologize.
