### ISSUE TITLE
Use system keychain for tokens

### ISSUE THREAD

**Issue by arjun27** [karigari/vscode-chat#77]
We can use [keytar](https://www.npmjs.com/package/keytar) to save sensitive tokens in the system keychain.

Couple of things to keep in mind:

- This change will need to migrate tokens for the existing installations
- keytar has system dependencies which will need to be managed (especially for Linux)

**Comment by mittalyashu** [comment]
Check this out https://github.com/karigari/vscode-chat/issues/74#issuecomment-417567625

**Comment by arjun27** [comment]
Released with 0.5.8
