### ISSUE TITLE
[vscode] Add new chat provider

### ISSUE THREAD

**Issue by iamgrawal** [karigari/vscode-chat#86]
My chat provider is: 

- Extension Version: 0.5.7
- OS Version: Linux x64 4.14.66-1-MANJARO
- VSCode version: 1.26.1

**Comment by mittalyashu** [comment]
@iamgrawal Which chat you want to be added to `vscode-chat`?

**Comment by mittalyashu** [comment]
@arjun27 can you look into this?

**Comment by iamgrawal** [comment]
@mittalyashu A suggestion, there is a lot of time when we don't want to integrate slack chat in vs code, instead we want to have a standalone chat option that is active during the live sharing duration. Can we have that?

**Comment by mittalyashu** [comment]
What you meant by standalone chat option?

Are you referring to this issue #87?

**Comment by iamgrawal** [comment]
yup, exactly.

**Comment by iamgrawal** [comment]
@arjun27 Thanks for the reply. 

I have made a screencast showing the issue ```access_denied```. Here it is: 

![error](https://user-images.githubusercontent.com/14204344/44988609-eb30a380-afa8-11e8-8190-a8efc3ca45b2.gif)

**Comment by iamgrawal** [comment]
@arjun27 Okay thanks a lot.
