### ISSUE TITLE
Use multiple chat providers concurrently

### ISSUE THREAD

**Issue by mittalyashu** [karigari/vscode-chat#88]
Multiple account means: Multiple slack workspace, multiple flock teams.

**Comment by enozero** [comment]
Yes, please! I work in multiple Slack workspaces, so this would be a great add for me to use it.

**Comment by arjun27** [comment]
Thanks for sharing @enozero. We are tracking multiple Slack workspaces in #26 - which is in the backlog. You can expect us releasing that this month. 

This issue is about multiple chat providers together - I'll rename this

**Comment by enozero** [comment]
Ah, perfect. Thanks!

**Comment by arjun27** [comment]
with 0.9.0, we can run multiple chat providers concurrently. By default, if you have live share installed, Team Chat supports running slack/discord and live share chat concurrently.
