### ISSUE TITLE
[vscode] Add new chat provider: Discord

### ISSUE THREAD

**Issue by mittalyashu** [karigari/vscode-chat#91]
There are lot of open source project using Discord as a tool for communication (React, Vue.js, Nuxt.js).

With the integration in the VS Code directly, it can be really easy to chat with the community and ask question without leaving the code editor.

**Comment by arjun27** [comment]
@mittalyashu, we have a pre-release build that supports Discord; you can set it up by following [these instructions](https://github.com/karigari/vscode-chat/pull/101#issuecomment-419648331). Please share if there is anything that does not work for you

**Comment by arjun27** [comment]
Discord support is available in v0.6.0. Please see [this doc](https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md) to setup your Discord account.
